version: '3.9'

services:
  # Zookeeper node 1
  zookeeper1:
    image: zookeeper:3.9.3
    container_name: zookeeper1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    volumes:
      - /tmp/zookeeper1/data
    networks:
      - kafka-network
    restart: always

  # Zookeeper node 2
  zookeeper2:
    image: zookeeper:3.9.3
    container_name: zookeeper2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2182:2181"
    volumes:
      - /tmp/zookeeper2/data
    networks:
      - kafka-network
    restart: always

  # Zookeeper node 3
  zookeeper3:
    image: zookeeper:3.9.3
    container_name: zookeeper3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2183:2181"
    volumes:
      - /tmp/zookeeper3/data
    networks:
      - kafka-network
    restart: always

  # Kafka Broker 1
  kafka1:
    image: bitnami/kafka:3.3
    container_name: kafka1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M -XX:ParallelGCThreads=1
      KAFKA_OPTS: -Dlogging.level=INFO

      # ZooKeeper và Kafka broker cấu hình
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9091,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      # KAFKA_LISTENER_NAME_INTERNAL: INTERNAL
      # KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL

      KAFKA_NUM_IO_THREADS: 8
      KAFKA_NUM_NETWORK_THREADS: 8
      KAFKA_NUM_REPLICA_FETCHERS: 2
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
    ports:
      - "9091:9091"
      - "9092:9092"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - kafka-network
    restart: always

  # Kafka Broker 2
  kafka2:
    image: bitnami/kafka:3.3
    container_name: kafka2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M -XX:ParallelGCThreads=1
      KAFKA_OPTS: -Dlogging.level=INFO

      # ZooKeeper và Kafka broker cấu hình
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9093,EXTERNAL://localhost:9094
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      # KAFKA_LISTENER_NAME_INTERNAL: INTERNAL
      # KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL

      KAFKA_NUM_IO_THREADS: 8
      KAFKA_NUM_NETWORK_THREADS: 8
      KAFKA_NUM_REPLICA_FETCHERS: 2
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
    ports:
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - kafka-network
    restart: always

  # Kafka Broker 3
  kafka3:
    image: bitnami/kafka:3.3
    container_name: kafka3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M -XX:ParallelGCThreads=1
      KAFKA_OPTS: -Dlogging.level=INFO

      # ZooKeeper và Kafka broker cấu hình
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9095,EXTERNAL://localhost:9096
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9095,EXTERNAL://0.0.0.0:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      # KAFKA_LISTENER_NAME_INTERNAL: INTERNAL
      # KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL

      KAFKA_NUM_IO_THREADS: 8
      KAFKA_NUM_NETWORK_THREADS: 8
      KAFKA_NUM_REPLICA_FETCHERS: 2
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
    ports:
      - "9095:9095"
      - "9096:9096"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - kafka-network
    restart: always

networks:
  kafka-network:
    driver: bridge
